#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHANSU2")]
	public partial class dbQLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUCNANG(CHUCNANG instance);
    partial void UpdateCHUCNANG(CHUCNANG instance);
    partial void DeleteCHUCNANG(CHUCNANG instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    partial void Inserttb_BOPHAN(tb_BOPHAN instance);
    partial void Updatetb_BOPHAN(tb_BOPHAN instance);
    partial void Deletetb_BOPHAN(tb_BOPHAN instance);
    partial void Inserttb_CHUCVU(tb_CHUCVU instance);
    partial void Updatetb_CHUCVU(tb_CHUCVU instance);
    partial void Deletetb_CHUCVU(tb_CHUCVU instance);
    partial void Inserttb_DANTOC(tb_DANTOC instance);
    partial void Updatetb_DANTOC(tb_DANTOC instance);
    partial void Deletetb_DANTOC(tb_DANTOC instance);
    partial void Inserttb_PHONGBAN(tb_PHONGBAN instance);
    partial void Updatetb_PHONGBAN(tb_PHONGBAN instance);
    partial void Deletetb_PHONGBAN(tb_PHONGBAN instance);
    partial void Inserttb_TONGIAO(tb_TONGIAO instance);
    partial void Updatetb_TONGIAO(tb_TONGIAO instance);
    partial void Deletetb_TONGIAO(tb_TONGIAO instance);
    partial void Inserttb_TRINHDO(tb_TRINHDO instance);
    partial void Updatetb_TRINHDO(tb_TRINHDO instance);
    partial void Deletetb_TRINHDO(tb_TRINHDO instance);
    partial void Inserttb_NHANVIEN(tb_NHANVIEN instance);
    partial void Updatetb_NHANVIEN(tb_NHANVIEN instance);
    partial void Deletetb_NHANVIEN(tb_NHANVIEN instance);
    partial void InsertBANGLUONG(BANGLUONG instance);
    partial void UpdateBANGLUONG(BANGLUONG instance);
    partial void DeleteBANGLUONG(BANGLUONG instance);
    partial void Inserttb_KYLUAT(tb_KYLUAT instance);
    partial void Updatetb_KYLUAT(tb_KYLUAT instance);
    partial void Deletetb_KYLUAT(tb_KYLUAT instance);
    partial void Inserttb_KHENTHUONG(tb_KHENTHUONG instance);
    partial void Updatetb_KHENTHUONG(tb_KHENTHUONG instance);
    partial void Deletetb_KHENTHUONG(tb_KHENTHUONG instance);
    partial void Inserttb_BANGCONG(tb_BANGCONG instance);
    partial void Updatetb_BANGCONG(tb_BANGCONG instance);
    partial void Deletetb_BANGCONG(tb_BANGCONG instance);
    partial void InsertHOTRO(HOTRO instance);
    partial void UpdateHOTRO(HOTRO instance);
    partial void DeleteHOTRO(HOTRO instance);
    partial void InsertDONDUYET(DONDUYET instance);
    partial void UpdateDONDUYET(DONDUYET instance);
    partial void DeleteDONDUYET(DONDUYET instance);
    #endregion
		
		public dbQLNSDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QUANLYNHANSU2ConnectionString"].ConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public dbQLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUCNANG> CHUCNANGs
		{
			get
			{
				return this.GetTable<CHUCNANG>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<tb_BOPHAN> tb_BOPHANs
		{
			get
			{
				return this.GetTable<tb_BOPHAN>();
			}
		}
		
		public System.Data.Linq.Table<tb_CHUCVU> tb_CHUCVUs
		{
			get
			{
				return this.GetTable<tb_CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<tb_DANTOC> tb_DANTOCs
		{
			get
			{
				return this.GetTable<tb_DANTOC>();
			}
		}
		
		public System.Data.Linq.Table<tb_PHONGBAN> tb_PHONGBANs
		{
			get
			{
				return this.GetTable<tb_PHONGBAN>();
			}
		}
		
		public System.Data.Linq.Table<tb_TONGIAO> tb_TONGIAOs
		{
			get
			{
				return this.GetTable<tb_TONGIAO>();
			}
		}
		
		public System.Data.Linq.Table<tb_TRINHDO> tb_TRINHDOs
		{
			get
			{
				return this.GetTable<tb_TRINHDO>();
			}
		}
		
		public System.Data.Linq.Table<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this.GetTable<tb_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<BANGLUONG> BANGLUONGs
		{
			get
			{
				return this.GetTable<BANGLUONG>();
			}
		}
		
		public System.Data.Linq.Table<tb_KYLUAT> tb_KYLUATs
		{
			get
			{
				return this.GetTable<tb_KYLUAT>();
			}
		}
		
		public System.Data.Linq.Table<tb_KHENTHUONG> tb_KHENTHUONGs
		{
			get
			{
				return this.GetTable<tb_KHENTHUONG>();
			}
		}
		
		public System.Data.Linq.Table<tb_BANGCONG> tb_BANGCONGs
		{
			get
			{
				return this.GetTable<tb_BANGCONG>();
			}
		}
		
		public System.Data.Linq.Table<HOTRO> HOTROs
		{
			get
			{
				return this.GetTable<HOTRO>();
			}
		}
		
		public System.Data.Linq.Table<DONDUYET> DONDUYETs
		{
			get
			{
				return this.GetTable<DONDUYET>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCNANG")]
	public partial class CHUCNANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACHUCNANG;
		
		private string _TENCHUCNANG;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCNANGChanging(int value);
    partial void OnMACHUCNANGChanged();
    partial void OnTENCHUCNANGChanging(string value);
    partial void OnTENCHUCNANGChanged();
    #endregion
		
		public CHUCNANG()
		{
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCNANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACHUCNANG
		{
			get
			{
				return this._MACHUCNANG;
			}
			set
			{
				if ((this._MACHUCNANG != value))
				{
					this.OnMACHUCNANGChanging(value);
					this.SendPropertyChanging();
					this._MACHUCNANG = value;
					this.SendPropertyChanged("MACHUCNANG");
					this.OnMACHUCNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCNANG", DbType="NVarChar(50)")]
		public string TENCHUCNANG
		{
			get
			{
				return this._TENCHUCNANG;
			}
			set
			{
				if ((this._TENCHUCNANG != value))
				{
					this.OnTENCHUCNANGChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCNANG = value;
					this.SendPropertyChanged("TENCHUCNANG");
					this.OnTENCHUCNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCNANG_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="MACHUCNANG", OtherKey="MACHUCNANG")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCNANG = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCNANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACHUCNANG;
		
		private int _MANV;
		
		private EntityRef<CHUCNANG> _CHUCNANG;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCNANGChanging(int value);
    partial void OnMACHUCNANGChanged();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    #endregion
		
		public PHANQUYEN()
		{
			this._CHUCNANG = default(EntityRef<CHUCNANG>);
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCNANG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACHUCNANG
		{
			get
			{
				return this._MACHUCNANG;
			}
			set
			{
				if ((this._MACHUCNANG != value))
				{
					if (this._CHUCNANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCNANGChanging(value);
					this.SendPropertyChanging();
					this._MACHUCNANG = value;
					this.SendPropertyChanged("MACHUCNANG");
					this.OnMACHUCNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCNANG_PHANQUYEN", Storage="_CHUCNANG", ThisKey="MACHUCNANG", OtherKey="MACHUCNANG", IsForeignKey=true)]
		public CHUCNANG CHUCNANG
		{
			get
			{
				return this._CHUCNANG.Entity;
			}
			set
			{
				CHUCNANG previousValue = this._CHUCNANG.Entity;
				if (((previousValue != value) 
							|| (this._CHUCNANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCNANG.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._CHUCNANG.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._MACHUCNANG = value.MACHUCNANG;
					}
					else
					{
						this._MACHUCNANG = default(int);
					}
					this.SendPropertyChanged("CHUCNANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_PHANQUYEN", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.PHANQUYENs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHANQUYENs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(int);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BOPHAN")]
	public partial class tb_BOPHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBP;
		
		private string _TENBP;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBPChanging(int value);
    partial void OnIDBPChanged();
    partial void OnTENBPChanging(string value);
    partial void OnTENBPChanged();
    #endregion
		
		public tb_BOPHAN()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBP
		{
			get
			{
				return this._IDBP;
			}
			set
			{
				if ((this._IDBP != value))
				{
					this.OnIDBPChanging(value);
					this.SendPropertyChanging();
					this._IDBP = value;
					this.SendPropertyChanged("IDBP");
					this.OnIDBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBP", DbType="NVarChar(50)")]
		public string TENBP
		{
			get
			{
				return this._TENBP;
			}
			set
			{
				if ((this._TENBP != value))
				{
					this.OnTENBPChanging(value);
					this.SendPropertyChanging();
					this._TENBP = value;
					this.SendPropertyChanged("TENBP");
					this.OnTENBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BOPHAN_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDBP", OtherKey="IDBP")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_BOPHAN = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_BOPHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_CHUCVU")]
	public partial class tb_CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCV;
		
		private string _TENCV;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCVChanging(int value);
    partial void OnIDCVChanged();
    partial void OnTENCVChanging(string value);
    partial void OnTENCVChanged();
    #endregion
		
		public tb_CHUCVU()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCV
		{
			get
			{
				return this._IDCV;
			}
			set
			{
				if ((this._IDCV != value))
				{
					this.OnIDCVChanging(value);
					this.SendPropertyChanging();
					this._IDCV = value;
					this.SendPropertyChanged("IDCV");
					this.OnIDCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCV", DbType="NVarChar(50)")]
		public string TENCV
		{
			get
			{
				return this._TENCV;
			}
			set
			{
				if ((this._TENCV != value))
				{
					this.OnTENCVChanging(value);
					this.SendPropertyChanging();
					this._TENCV = value;
					this.SendPropertyChanged("TENCV");
					this.OnTENCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_CHUCVU_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDCV", OtherKey="IDCV")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_CHUCVU = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_DANTOC")]
	public partial class tb_DANTOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDT;
		
		private string _TENDT;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDTChanging(int value);
    partial void OnIDDTChanged();
    partial void OnTENDTChanging(string value);
    partial void OnTENDTChanged();
    #endregion
		
		public tb_DANTOC()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDT
		{
			get
			{
				return this._IDDT;
			}
			set
			{
				if ((this._IDDT != value))
				{
					this.OnIDDTChanging(value);
					this.SendPropertyChanging();
					this._IDDT = value;
					this.SendPropertyChanged("IDDT");
					this.OnIDDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDT", DbType="NVarChar(50)")]
		public string TENDT
		{
			get
			{
				return this._TENDT;
			}
			set
			{
				if ((this._TENDT != value))
				{
					this.OnTENDTChanging(value);
					this.SendPropertyChanging();
					this._TENDT = value;
					this.SendPropertyChanged("TENDT");
					this.OnTENDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_DANTOC_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDDT", OtherKey="IDDT")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_DANTOC = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_DANTOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_PHONGBAN")]
	public partial class tb_PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPB;
		
		private string _TENPB;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPBChanging(int value);
    partial void OnIDPBChanged();
    partial void OnTENPBChanging(string value);
    partial void OnTENPBChanged();
    #endregion
		
		public tb_PHONGBAN()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPB", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPB
		{
			get
			{
				return this._IDPB;
			}
			set
			{
				if ((this._IDPB != value))
				{
					this.OnIDPBChanging(value);
					this.SendPropertyChanging();
					this._IDPB = value;
					this.SendPropertyChanged("IDPB");
					this.OnIDPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPB", DbType="NVarChar(50)")]
		public string TENPB
		{
			get
			{
				return this._TENPB;
			}
			set
			{
				if ((this._TENPB != value))
				{
					this.OnTENPBChanging(value);
					this.SendPropertyChanging();
					this._TENPB = value;
					this.SendPropertyChanged("TENPB");
					this.OnTENPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PHONGBAN_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDPB", OtherKey="IDPB")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_PHONGBAN = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_PHONGBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_TONGIAO")]
	public partial class tb_TONGIAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTG;
		
		private string _TENTG;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTGChanging(int value);
    partial void OnIDTGChanged();
    partial void OnTENTGChanging(string value);
    partial void OnTENTGChanged();
    #endregion
		
		public tb_TONGIAO()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTG
		{
			get
			{
				return this._IDTG;
			}
			set
			{
				if ((this._IDTG != value))
				{
					this.OnIDTGChanging(value);
					this.SendPropertyChanging();
					this._IDTG = value;
					this.SendPropertyChanged("IDTG");
					this.OnIDTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTG", DbType="NVarChar(50)")]
		public string TENTG
		{
			get
			{
				return this._TENTG;
			}
			set
			{
				if ((this._TENTG != value))
				{
					this.OnTENTGChanging(value);
					this.SendPropertyChanging();
					this._TENTG = value;
					this.SendPropertyChanged("TENTG");
					this.OnTENTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TONGIAO_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDTG", OtherKey="IDTG")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_TONGIAO = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_TONGIAO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_TRINHDO")]
	public partial class tb_TRINHDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTD;
		
		private string _TENTD;
		
		private EntitySet<tb_NHANVIEN> _tb_NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTDChanging(int value);
    partial void OnIDTDChanged();
    partial void OnTENTDChanging(string value);
    partial void OnTENTDChanged();
    #endregion
		
		public tb_TRINHDO()
		{
			this._tb_NHANVIENs = new EntitySet<tb_NHANVIEN>(new Action<tb_NHANVIEN>(this.attach_tb_NHANVIENs), new Action<tb_NHANVIEN>(this.detach_tb_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTD
		{
			get
			{
				return this._IDTD;
			}
			set
			{
				if ((this._IDTD != value))
				{
					this.OnIDTDChanging(value);
					this.SendPropertyChanging();
					this._IDTD = value;
					this.SendPropertyChanged("IDTD");
					this.OnIDTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTD", DbType="NVarChar(50)")]
		public string TENTD
		{
			get
			{
				return this._TENTD;
			}
			set
			{
				if ((this._TENTD != value))
				{
					this.OnTENTDChanging(value);
					this.SendPropertyChanging();
					this._TENTD = value;
					this.SendPropertyChanged("TENTD");
					this.OnTENTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TRINHDO_tb_NHANVIEN", Storage="_tb_NHANVIENs", ThisKey="IDTD", OtherKey="IDTD")]
		public EntitySet<tb_NHANVIEN> tb_NHANVIENs
		{
			get
			{
				return this._tb_NHANVIENs;
			}
			set
			{
				this._tb_NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_TRINHDO = this;
		}
		
		private void detach_tb_NHANVIENs(tb_NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_TRINHDO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_NHANVIEN")]
	public partial class tb_NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANV;
		
		private string _HOTEN;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIENTHOAI;
		
		private string _EMAIL;
		
		private string _MATKHAU;
		
		private string _CCCD;
		
		private string _DIACHI;
		
		private string _HINHANH;
		
		private System.Nullable<int> _IDPB;
		
		private System.Nullable<int> _IDBP;
		
		private System.Nullable<int> _IDCV;
		
		private System.Nullable<int> _IDTD;
		
		private System.Nullable<int> _IDDT;
		
		private System.Nullable<int> _IDTG;
		
		private EntitySet<PHANQUYEN> _PHANQUYENs;
		
		private EntitySet<BANGLUONG> _BANGLUONGs;
		
		private EntitySet<tb_KYLUAT> _tb_KYLUATs;
		
		private EntitySet<tb_KHENTHUONG> _tb_KHENTHUONGs;
		
		private EntitySet<tb_BANGCONG> _tb_BANGCONGs;
		
		private EntitySet<DONDUYET> _DONDUYETs;
		
		private EntityRef<tb_BOPHAN> _tb_BOPHAN;
		
		private EntityRef<tb_CHUCVU> _tb_CHUCVU;
		
		private EntityRef<tb_DANTOC> _tb_DANTOC;
		
		private EntityRef<tb_PHONGBAN> _tb_PHONGBAN;
		
		private EntityRef<tb_TONGIAO> _tb_TONGIAO;
		
		private EntityRef<tb_TRINHDO> _tb_TRINHDO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnIDPBChanging(System.Nullable<int> value);
    partial void OnIDPBChanged();
    partial void OnIDBPChanging(System.Nullable<int> value);
    partial void OnIDBPChanged();
    partial void OnIDCVChanging(System.Nullable<int> value);
    partial void OnIDCVChanged();
    partial void OnIDTDChanging(System.Nullable<int> value);
    partial void OnIDTDChanged();
    partial void OnIDDTChanging(System.Nullable<int> value);
    partial void OnIDDTChanged();
    partial void OnIDTGChanging(System.Nullable<int> value);
    partial void OnIDTGChanged();
    #endregion
		
		public tb_NHANVIEN()
		{
			this._PHANQUYENs = new EntitySet<PHANQUYEN>(new Action<PHANQUYEN>(this.attach_PHANQUYENs), new Action<PHANQUYEN>(this.detach_PHANQUYENs));
			this._BANGLUONGs = new EntitySet<BANGLUONG>(new Action<BANGLUONG>(this.attach_BANGLUONGs), new Action<BANGLUONG>(this.detach_BANGLUONGs));
			this._tb_KYLUATs = new EntitySet<tb_KYLUAT>(new Action<tb_KYLUAT>(this.attach_tb_KYLUATs), new Action<tb_KYLUAT>(this.detach_tb_KYLUATs));
			this._tb_KHENTHUONGs = new EntitySet<tb_KHENTHUONG>(new Action<tb_KHENTHUONG>(this.attach_tb_KHENTHUONGs), new Action<tb_KHENTHUONG>(this.detach_tb_KHENTHUONGs));
			this._tb_BANGCONGs = new EntitySet<tb_BANGCONG>(new Action<tb_BANGCONG>(this.attach_tb_BANGCONGs), new Action<tb_BANGCONG>(this.detach_tb_BANGCONGs));
			this._DONDUYETs = new EntitySet<DONDUYET>(new Action<DONDUYET>(this.attach_DONDUYETs), new Action<DONDUYET>(this.detach_DONDUYETs));
			this._tb_BOPHAN = default(EntityRef<tb_BOPHAN>);
			this._tb_CHUCVU = default(EntityRef<tb_CHUCVU>);
			this._tb_DANTOC = default(EntityRef<tb_DANTOC>);
			this._tb_PHONGBAN = default(EntityRef<tb_PHONGBAN>);
			this._tb_TONGIAO = default(EntityRef<tb_TONGIAO>);
			this._tb_TRINHDO = default(EntityRef<tb_TRINHDO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(50)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(50)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(50)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(50)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(300)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(100)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPB", DbType="Int")]
		public System.Nullable<int> IDPB
		{
			get
			{
				return this._IDPB;
			}
			set
			{
				if ((this._IDPB != value))
				{
					if (this._tb_PHONGBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPBChanging(value);
					this.SendPropertyChanging();
					this._IDPB = value;
					this.SendPropertyChanged("IDPB");
					this.OnIDPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBP", DbType="Int")]
		public System.Nullable<int> IDBP
		{
			get
			{
				return this._IDBP;
			}
			set
			{
				if ((this._IDBP != value))
				{
					if (this._tb_BOPHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBPChanging(value);
					this.SendPropertyChanging();
					this._IDBP = value;
					this.SendPropertyChanged("IDBP");
					this.OnIDBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCV", DbType="Int")]
		public System.Nullable<int> IDCV
		{
			get
			{
				return this._IDCV;
			}
			set
			{
				if ((this._IDCV != value))
				{
					if (this._tb_CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCVChanging(value);
					this.SendPropertyChanging();
					this._IDCV = value;
					this.SendPropertyChanged("IDCV");
					this.OnIDCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTD", DbType="Int")]
		public System.Nullable<int> IDTD
		{
			get
			{
				return this._IDTD;
			}
			set
			{
				if ((this._IDTD != value))
				{
					if (this._tb_TRINHDO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTDChanging(value);
					this.SendPropertyChanging();
					this._IDTD = value;
					this.SendPropertyChanged("IDTD");
					this.OnIDTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDT", DbType="Int")]
		public System.Nullable<int> IDDT
		{
			get
			{
				return this._IDDT;
			}
			set
			{
				if ((this._IDDT != value))
				{
					if (this._tb_DANTOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDTChanging(value);
					this.SendPropertyChanging();
					this._IDDT = value;
					this.SendPropertyChanged("IDDT");
					this.OnIDDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTG", DbType="Int")]
		public System.Nullable<int> IDTG
		{
			get
			{
				return this._IDTG;
			}
			set
			{
				if ((this._IDTG != value))
				{
					if (this._tb_TONGIAO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTGChanging(value);
					this.SendPropertyChanging();
					this._IDTG = value;
					this.SendPropertyChanged("IDTG");
					this.OnIDTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_PHANQUYEN", Storage="_PHANQUYENs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this._PHANQUYENs;
			}
			set
			{
				this._PHANQUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_BANGLUONG", Storage="_BANGLUONGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<BANGLUONG> BANGLUONGs
		{
			get
			{
				return this._BANGLUONGs;
			}
			set
			{
				this._BANGLUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_KYLUAT", Storage="_tb_KYLUATs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<tb_KYLUAT> tb_KYLUATs
		{
			get
			{
				return this._tb_KYLUATs;
			}
			set
			{
				this._tb_KYLUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_KHENTHUONG", Storage="_tb_KHENTHUONGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<tb_KHENTHUONG> tb_KHENTHUONGs
		{
			get
			{
				return this._tb_KHENTHUONGs;
			}
			set
			{
				this._tb_KHENTHUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_BANGCONG", Storage="_tb_BANGCONGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<tb_BANGCONG> tb_BANGCONGs
		{
			get
			{
				return this._tb_BANGCONGs;
			}
			set
			{
				this._tb_BANGCONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_DONDUYET", Storage="_DONDUYETs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<DONDUYET> DONDUYETs
		{
			get
			{
				return this._DONDUYETs;
			}
			set
			{
				this._DONDUYETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_BOPHAN_tb_NHANVIEN", Storage="_tb_BOPHAN", ThisKey="IDBP", OtherKey="IDBP", IsForeignKey=true)]
		public tb_BOPHAN tb_BOPHAN
		{
			get
			{
				return this._tb_BOPHAN.Entity;
			}
			set
			{
				tb_BOPHAN previousValue = this._tb_BOPHAN.Entity;
				if (((previousValue != value) 
							|| (this._tb_BOPHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_BOPHAN.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_BOPHAN.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDBP = value.IDBP;
					}
					else
					{
						this._IDBP = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_BOPHAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_CHUCVU_tb_NHANVIEN", Storage="_tb_CHUCVU", ThisKey="IDCV", OtherKey="IDCV", IsForeignKey=true)]
		public tb_CHUCVU tb_CHUCVU
		{
			get
			{
				return this._tb_CHUCVU.Entity;
			}
			set
			{
				tb_CHUCVU previousValue = this._tb_CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._tb_CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_CHUCVU.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_CHUCVU.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDCV = value.IDCV;
					}
					else
					{
						this._IDCV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_CHUCVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_DANTOC_tb_NHANVIEN", Storage="_tb_DANTOC", ThisKey="IDDT", OtherKey="IDDT", IsForeignKey=true)]
		public tb_DANTOC tb_DANTOC
		{
			get
			{
				return this._tb_DANTOC.Entity;
			}
			set
			{
				tb_DANTOC previousValue = this._tb_DANTOC.Entity;
				if (((previousValue != value) 
							|| (this._tb_DANTOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_DANTOC.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_DANTOC.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDDT = value.IDDT;
					}
					else
					{
						this._IDDT = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_DANTOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_PHONGBAN_tb_NHANVIEN", Storage="_tb_PHONGBAN", ThisKey="IDPB", OtherKey="IDPB", IsForeignKey=true)]
		public tb_PHONGBAN tb_PHONGBAN
		{
			get
			{
				return this._tb_PHONGBAN.Entity;
			}
			set
			{
				tb_PHONGBAN previousValue = this._tb_PHONGBAN.Entity;
				if (((previousValue != value) 
							|| (this._tb_PHONGBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_PHONGBAN.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_PHONGBAN.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDPB = value.IDPB;
					}
					else
					{
						this._IDPB = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_PHONGBAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TONGIAO_tb_NHANVIEN", Storage="_tb_TONGIAO", ThisKey="IDTG", OtherKey="IDTG", IsForeignKey=true)]
		public tb_TONGIAO tb_TONGIAO
		{
			get
			{
				return this._tb_TONGIAO.Entity;
			}
			set
			{
				tb_TONGIAO previousValue = this._tb_TONGIAO.Entity;
				if (((previousValue != value) 
							|| (this._tb_TONGIAO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_TONGIAO.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_TONGIAO.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDTG = value.IDTG;
					}
					else
					{
						this._IDTG = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_TONGIAO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_TRINHDO_tb_NHANVIEN", Storage="_tb_TRINHDO", ThisKey="IDTD", OtherKey="IDTD", IsForeignKey=true)]
		public tb_TRINHDO tb_TRINHDO
		{
			get
			{
				return this._tb_TRINHDO.Entity;
			}
			set
			{
				tb_TRINHDO previousValue = this._tb_TRINHDO.Entity;
				if (((previousValue != value) 
							|| (this._tb_TRINHDO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_TRINHDO.Entity = null;
						previousValue.tb_NHANVIENs.Remove(this);
					}
					this._tb_TRINHDO.Entity = value;
					if ((value != null))
					{
						value.tb_NHANVIENs.Add(this);
						this._IDTD = value.IDTD;
					}
					else
					{
						this._IDTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_TRINHDO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_PHANQUYENs(PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
		
		private void attach_BANGLUONGs(BANGLUONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_BANGLUONGs(BANGLUONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
		
		private void attach_tb_KYLUATs(tb_KYLUAT entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_tb_KYLUATs(tb_KYLUAT entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
		
		private void attach_tb_KHENTHUONGs(tb_KHENTHUONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_tb_KHENTHUONGs(tb_KHENTHUONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
		
		private void attach_tb_BANGCONGs(tb_BANGCONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_tb_BANGCONGs(tb_BANGCONG entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
		
		private void attach_DONDUYETs(DONDUYET entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = this;
		}
		
		private void detach_DONDUYETs(DONDUYET entity)
		{
			this.SendPropertyChanging();
			entity.tb_NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGLUONG")]
	public partial class BANGLUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALUONG;
		
		private string _TENNV;
		
		private System.Nullable<int> _MANV;
		
		private System.Nullable<int> _SONGAYLAM;
		
		private System.Nullable<double> _HESOLUONG;
		
		private System.Nullable<double> _THUONG;
		
		private System.Nullable<double> _TONGLUONG;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALUONGChanging(int value);
    partial void OnMALUONGChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    partial void OnSONGAYLAMChanging(System.Nullable<int> value);
    partial void OnSONGAYLAMChanged();
    partial void OnHESOLUONGChanging(System.Nullable<double> value);
    partial void OnHESOLUONGChanged();
    partial void OnTHUONGChanging(System.Nullable<double> value);
    partial void OnTHUONGChanged();
    partial void OnTONGLUONGChanging(System.Nullable<double> value);
    partial void OnTONGLUONGChanged();
    #endregion
		
		public BANGLUONG()
		{
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALUONG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MALUONG
		{
			get
			{
				return this._MALUONG;
			}
			set
			{
				if ((this._MALUONG != value))
				{
					this.OnMALUONGChanging(value);
					this.SendPropertyChanging();
					this._MALUONG = value;
					this.SendPropertyChanged("MALUONG");
					this.OnMALUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(50)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAYLAM", DbType="Int")]
		public System.Nullable<int> SONGAYLAM
		{
			get
			{
				return this._SONGAYLAM;
			}
			set
			{
				if ((this._SONGAYLAM != value))
				{
					this.OnSONGAYLAMChanging(value);
					this.SendPropertyChanging();
					this._SONGAYLAM = value;
					this.SendPropertyChanged("SONGAYLAM");
					this.OnSONGAYLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESOLUONG", DbType="Float")]
		public System.Nullable<double> HESOLUONG
		{
			get
			{
				return this._HESOLUONG;
			}
			set
			{
				if ((this._HESOLUONG != value))
				{
					this.OnHESOLUONGChanging(value);
					this.SendPropertyChanging();
					this._HESOLUONG = value;
					this.SendPropertyChanged("HESOLUONG");
					this.OnHESOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUONG", DbType="Float")]
		public System.Nullable<double> THUONG
		{
			get
			{
				return this._THUONG;
			}
			set
			{
				if ((this._THUONG != value))
				{
					this.OnTHUONGChanging(value);
					this.SendPropertyChanging();
					this._THUONG = value;
					this.SendPropertyChanged("THUONG");
					this.OnTHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGLUONG", DbType="Float")]
		public System.Nullable<double> TONGLUONG
		{
			get
			{
				return this._TONGLUONG;
			}
			set
			{
				if ((this._TONGLUONG != value))
				{
					this.OnTONGLUONGChanging(value);
					this.SendPropertyChanging();
					this._TONGLUONG = value;
					this.SendPropertyChanged("TONGLUONG");
					this.OnTONGLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_BANGLUONG", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.BANGLUONGs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.BANGLUONGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_KYLUAT")]
	public partial class tb_KYLUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKYLUAT;
		
		private System.Nullable<int> _MANV;
		
		private string _LYDO;
		
		private string _NOIDUNG;
		
		private string _TENNV;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKYLUATChanging(int value);
    partial void OnMAKYLUATChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    #endregion
		
		public tb_KYLUAT()
		{
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKYLUAT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAKYLUAT
		{
			get
			{
				return this._MAKYLUAT;
			}
			set
			{
				if ((this._MAKYLUAT != value))
				{
					this.OnMAKYLUATChanging(value);
					this.SendPropertyChanging();
					this._MAKYLUAT = value;
					this.SendPropertyChanged("MAKYLUAT");
					this.OnMAKYLUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(50)")]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(50)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(30)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_KYLUAT", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.tb_KYLUATs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tb_KYLUATs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_KHENTHUONG")]
	public partial class tb_KHENTHUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKHENTHUONG;
		
		private System.Nullable<int> _MANV;
		
		private string _LYDO;
		
		private string _NOIDUNG;
		
		private string _TENNV;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHENTHUONGChanging(int value);
    partial void OnMAKHENTHUONGChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    #endregion
		
		public tb_KHENTHUONG()
		{
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHENTHUONG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKHENTHUONG
		{
			get
			{
				return this._MAKHENTHUONG;
			}
			set
			{
				if ((this._MAKHENTHUONG != value))
				{
					this.OnMAKHENTHUONGChanging(value);
					this.SendPropertyChanging();
					this._MAKHENTHUONG = value;
					this.SendPropertyChanged("MAKHENTHUONG");
					this.OnMAKHENTHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(50)")]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(50)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(30)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_KHENTHUONG", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.tb_KHENTHUONGs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tb_KHENTHUONGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_BANGCONG")]
	public partial class tb_BANGCONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACONG;
		
		private string _TENNV;
		
		private System.Nullable<int> _MANV;
		
		private string _TENCV;
		
		private string _TENPB;
		
		private System.Nullable<System.DateTime> _NGAYGIOLAM;
		
		private System.Nullable<System.DateTime> _NGAYGIORA;
		
		private System.Nullable<int> _TONGGIOLAM;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACONGChanging(int value);
    partial void OnMACONGChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    partial void OnTENCVChanging(string value);
    partial void OnTENCVChanged();
    partial void OnTENPBChanging(string value);
    partial void OnTENPBChanged();
    partial void OnNGAYGIOLAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIOLAMChanged();
    partial void OnNGAYGIORAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIORAChanged();
    partial void OnTONGGIOLAMChanging(System.Nullable<int> value);
    partial void OnTONGGIOLAMChanged();
    #endregion
		
		public tb_BANGCONG()
		{
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACONG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACONG
		{
			get
			{
				return this._MACONG;
			}
			set
			{
				if ((this._MACONG != value))
				{
					this.OnMACONGChanging(value);
					this.SendPropertyChanging();
					this._MACONG = value;
					this.SendPropertyChanged("MACONG");
					this.OnMACONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(100)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCV", DbType="NVarChar(50)")]
		public string TENCV
		{
			get
			{
				return this._TENCV;
			}
			set
			{
				if ((this._TENCV != value))
				{
					this.OnTENCVChanging(value);
					this.SendPropertyChanging();
					this._TENCV = value;
					this.SendPropertyChanged("TENCV");
					this.OnTENCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPB", DbType="NVarChar(50)")]
		public string TENPB
		{
			get
			{
				return this._TENPB;
			}
			set
			{
				if ((this._TENPB != value))
				{
					this.OnTENPBChanging(value);
					this.SendPropertyChanging();
					this._TENPB = value;
					this.SendPropertyChanged("TENPB");
					this.OnTENPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIOLAM", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIOLAM
		{
			get
			{
				return this._NGAYGIOLAM;
			}
			set
			{
				if ((this._NGAYGIOLAM != value))
				{
					this.OnNGAYGIOLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIOLAM = value;
					this.SendPropertyChanged("NGAYGIOLAM");
					this.OnNGAYGIOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIORA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIORA
		{
			get
			{
				return this._NGAYGIORA;
			}
			set
			{
				if ((this._NGAYGIORA != value))
				{
					this.OnNGAYGIORAChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIORA = value;
					this.SendPropertyChanged("NGAYGIORA");
					this.OnNGAYGIORAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGGIOLAM", DbType="Int")]
		public System.Nullable<int> TONGGIOLAM
		{
			get
			{
				return this._TONGGIOLAM;
			}
			set
			{
				if ((this._TONGGIOLAM != value))
				{
					this.OnTONGGIOLAMChanging(value);
					this.SendPropertyChanging();
					this._TONGGIOLAM = value;
					this.SendPropertyChanged("TONGGIOLAM");
					this.OnTONGGIOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_tb_BANGCONG", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.tb_BANGCONGs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tb_BANGCONGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOTRO")]
	public partial class HOTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHOTRO;
		
		private string _TENDONVI;
		
		private string _SDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOTROChanging(int value);
    partial void OnMAHOTROChanged();
    partial void OnTENDONVIChanging(string value);
    partial void OnTENDONVIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public HOTRO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOTRO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHOTRO
		{
			get
			{
				return this._MAHOTRO;
			}
			set
			{
				if ((this._MAHOTRO != value))
				{
					this.OnMAHOTROChanging(value);
					this.SendPropertyChanging();
					this._MAHOTRO = value;
					this.SendPropertyChanged("MAHOTRO");
					this.OnMAHOTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDONVI", DbType="NVarChar(50)")]
		public string TENDONVI
		{
			get
			{
				return this._TENDONVI;
			}
			set
			{
				if ((this._TENDONVI != value))
				{
					this.OnTENDONVIChanging(value);
					this.SendPropertyChanging();
					this._TENDONVI = value;
					this.SendPropertyChanged("TENDONVI");
					this.OnTENDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDUYET")]
	public partial class DONDUYET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADON;
		
		private int _MANV;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYLAPPHIEU;
		
		private string _TINHTRANG;
		
		private string _LYDO;
		
		private System.Nullable<System.DateTime> _NGAYXINNGHI;
		
		private string _PHONGBAN;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private EntityRef<tb_NHANVIEN> _tb_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADONChanging(int value);
    partial void OnMADONChanged();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYLAPPHIEUChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPPHIEUChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnNGAYXINNGHIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYXINNGHIChanged();
    partial void OnPHONGBANChanging(string value);
    partial void OnPHONGBANChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    #endregion
		
		public DONDUYET()
		{
			this._tb_NHANVIEN = default(EntityRef<tb_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADON
		{
			get
			{
				return this._MADON;
			}
			set
			{
				if ((this._MADON != value))
				{
					this.OnMADONChanging(value);
					this.SendPropertyChanging();
					this._MADON = value;
					this.SendPropertyChanged("MADON");
					this.OnMADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int NOT NULL")]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tb_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAPPHIEU", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAPPHIEU
		{
			get
			{
				return this._NGAYLAPPHIEU;
			}
			set
			{
				if ((this._NGAYLAPPHIEU != value))
				{
					this.OnNGAYLAPPHIEUChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAPPHIEU = value;
					this.SendPropertyChanged("NGAYLAPPHIEU");
					this.OnNGAYLAPPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(50)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(100)")]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYXINNGHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYXINNGHI
		{
			get
			{
				return this._NGAYXINNGHI;
			}
			set
			{
				if ((this._NGAYXINNGHI != value))
				{
					this.OnNGAYXINNGHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYXINNGHI = value;
					this.SendPropertyChanged("NGAYXINNGHI");
					this.OnNGAYXINNGHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGBAN", DbType="NVarChar(50)")]
		public string PHONGBAN
		{
			get
			{
				return this._PHONGBAN;
			}
			set
			{
				if ((this._PHONGBAN != value))
				{
					this.OnPHONGBANChanging(value);
					this.SendPropertyChanging();
					this._PHONGBAN = value;
					this.SendPropertyChanged("PHONGBAN");
					this.OnPHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_NHANVIEN_DONDUYET", Storage="_tb_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tb_NHANVIEN tb_NHANVIEN
		{
			get
			{
				return this._tb_NHANVIEN.Entity;
			}
			set
			{
				tb_NHANVIEN previousValue = this._tb_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tb_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_NHANVIEN.Entity = null;
						previousValue.DONDUYETs.Remove(this);
					}
					this._tb_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.DONDUYETs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(int);
					}
					this.SendPropertyChanged("tb_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
